### ISSUE TITLE
Playground Login redirect to the playground main page 

### ISSUE THREAD

**Issue by thhck** [NoelDeMartin/aerogel#2]
hi again :)

In the playground login feature its seems that the redirectin point to the wrong url. 
After clicking login on https://aerogel.js.org/playground/solid  and entering Pod credentials, the user get redirected to https://aerogel.js.org/playground/ .

As a user I'm expecting to go back to https://aerogel.js.org/playground/solid with a message showing me that I got logged in.

**Comment by NoelDeMartin** [comment]
This is actually how it was working until recently, but it seems like [implementing the ClientID](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/authenticate-client/) changed that behaviour.

The main problem here is that the ClientID document has to declare the `redirect_uris` of the app, and since I am only declaring the root url, that's the one being used.

I agree that what you mention is better, but I have to think how to do that automatically. For this playground in particular, there are only two urls where the user can log in: `/solid` and `/offline`. But for many apps, it's very likely that you can log in from anywhere. So I'll think about a solution for that.

**Comment by NoelDeMartin** [comment]
Fixed and deployed!
